spring:
  application:
    name: blogify
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
      enabled: true
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/book_connect
    username: replace_me_username
    password: replace_me_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.springframework: INFO

#user:
#  config:
#    jwt-secret-key: